### ISSUE TITLE
[IMPROVEMENT] Need for EIP-712 implementation?

### ISSUE THREAD

**Issue by madztheo** [PianoKing-NFT/Smart-Contract#3]
**Description**
The EIP-712 is an Ethereum Improvement proposal that actually didn't get finalized but has been partially implemented by multiple smart contracts. It allows to prove that a given signed transaction was signed on a specific chain (such as Ethereum mainnet, Rinkeby, Polygon, etc.) by a specific contract of a given name and version. This prevents replay attacks in which one person would sign a transaction interacting with the contract on one network such as a testnet like Rinkeby and execute it later on Ethereum mainnet.

Since the DAO will give rights to whoever owns a NFT of Piano King, most likely the process will work by signing messages with their private key proving that they own an NFT. The check might just be server-side, a regular signed message will be enough to prove ownership without this risk as the server will only check against the contract on mainnet. However we may need to use meta transactions to do other processes and in such cases it would be open to exploit. I couldn't think of a use case yet for meta transactions on the DAO. But the possibility seems non-negligible, so I'm wondering if we should implement the EIP-712 of OpenZeppelin to prevent ourselves trouble in the future https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.4.0/contracts/utils/cryptography/draft-EIP712.sol

**Comment by datgrog** [comment]
If I may clarify, [EIP-712](https://eips.ethereum.org/EIPS/eip-712) does not ensure that "_that a given signed transaction was signed on a specific chain_" (all field on transaction including `data`) but ensure that a given "Ethereum Typed Struct's payload" (sub part of the tx `data` field) is sign only for a specific chain which is not the same. Since the famous DAO hack ethereum effectively need to protect from "cross" transaction replay as it was possible to replay a transaction from ETH to ETC and vis versa (some exchange suffers from this as you could imagine...). So the solution was bring by the [EIP-155 "Spurious Dragon"](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) which took the chainId into account when signing a given transaction. It has been recently clean up a bit since [EIP-1559 "London"](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md).

A ~year+ ago spent many times around metatransaction and played around [Chai.money](https://mojkripto.com/chai-token-principal-and-interest-in-one/?lang=en), [Gasless](https://github.com/mosendo/gasless) and [ds-dach](https://github.com/dapphub/ds-dach/tree/master) (3 really nice starting point to understand "the whole flow"). The point was to support the Dai stablecoin on a wallet with its related passive income feature thanks to DSR in a "meta transaction" manner. So it allowed for someone without ETH to still interact with Dai by relaying his metatransaction to a relayer (backend, but could but more "resilient" with GSN in theorie) while paying his fee in Dai (or free if relayer accept).
My key takeaway are:
- All of this is possible/conditioned **only** if the related ERC20 you want to "metatransactioned" **support** the [permit](https://eips.ethereum.org/EIPS/eip-2612) method (which has a specific use case, which is an `approve`)
- If you relay something then obviously someone has to pay for the fee, which is the relayer by default as he embbed the signed payload struct on its `data` transaction
- Also, there are some [catch](https://github.com/makerdao/developerguides/blob/master/dai/how-to-use-permit-function/how-to-use-permit-function.md#note-on-security)

(IMO) So, to keep it short I would just say it's very cool and doable buut not worth it at this stage or for a V0. On the other hand, **PianoKing DAO only require a permit like fonction to support this functionality**, it's more? simple and **open the door for later support**. (Basically `permit` is a wrapped `approve` fonction where it consumes that payload of the ethereum typed struct relayed) I did not think about it but I guess it requires an `approve` like logic for delagating a vote the same way `approve` delegate the right to move some amount of token.

The regular signed message process (along with a expiration and stuff) you describe is simple and nice. Of course there is some trade-off, I don't know in your case if after the backend check signature it "count" the vote in db or directly one tx to update the DAO or count he entire vote then update the state in the DAO. Yes It's centralised anyway but it's a V0 of the voting process, and people could always vote directly to the DAO contract, where the DAO verify that the msg.sender own a pinaoking with a `balanceOf(owner, tokenId)` I suppose.

---

Edit: After reading again your message, I just notice that you don't see a use case yet and above I just take an example of a delagation of a vote. But implementing a "dynamic/genric" permit like on something you don't know yet does not looks possible.
It looks like you want an ethereum typed structured like a "json-rpc" which then need to be consumed by a proxy (updatable) into a "implement" contract that implement the feature asked by the typed struct but it feels wild and complicated or maybe I go way to far away

**Comment by madztheo** [comment]
Thanks for the clarification. It is not the same but you do end up with something that can prove that the transaction was coming from a specific chain, given that you implemented the necessary code to check the relevant Ethereum Typed structured data you want to accept. Which was my core point there.

Anyway, with the explanation you give it does seem that it would be hard to predict how to structure this properly without having a clear use case in mind yet. I guess we'll have to go either with the server-side option or deal directly with the DAO.
